node-001:
  global:
    main:
      network: 4844-devnet-6
      engineEndpoint: http://{{ .Release.Name }}-execution:8551
      rpcEndpoint: http://{{ .Release.Name }}-execution:8545
      beaconEndpoint: http://{{ .Release.Name }}-beacon:5052
    checkpointSync:
      enabled: false
  #Geth
  nethermind:
    fullnameOverride: nethermind-lodestar-001
    enabled: true
    image:
      repository: nethermindeth/nethermind
      tag: eip-4844-v6
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 50Gi
    podLabels:
      network: 4844-devnet-6
      testnet: 4844-devnet-6
      ethereum_network: 4844-devnet-6
      ethereum_role: execution
      consensus_client: lodestar
      execution_client: nethermind
      ethereum_instance: nethermind-lodestar-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    extraArgs:
      - --Discovery.Bootnodes="enode://f5c4a7b3b0d4b16853ff82e76732c9f61f13d3ce376d45af5a3de6cdff0305b1ee29c12a9ca885e4ccdf79fefc5a3eeb6ecb1fbd4b0473b4b2b8ef55cc07fb11@64.225.71.71:30303?discport=30303"
      - --Init.ChainSpecPath=/data/genesis.json
      - --config=none.cfg
      - --Init.IsMining=false
      - --Pruning.Mode=None
      - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
      - --EthStats.Enabled=true
      - --EthStats.Name=rpc-nethermind-lodestar
      - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.ethstats_secret}>
      - --EthStats.Server=wss://ethstats.4844-devnet-6.ethpandaops.io
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          BOOTNODE_URI=https://config.4844-devnet-6.ethpandaops.io/el/bootnodes;
          GENESIS_URI=https://config.4844-devnet-6.ethpandaops.io/el/chainspec.json;
          TRUSTED_SETUP_URI=https://config.4844-devnet-6.ethpandaops.io/trusted_setup.txt;
          if ! [ -f /data/genesis_init_done ];
          then
            wget -O /data/genesis.json $GENESIS_URI;
            wget -O /data/bootnodes.txt $BOOTNODE_URI;
            wget -O /data/trusted_setup.txt $TRUSTED_SETUP_URI;
            apk update && apk add jq;
            cat /data/genesis.json | jq -r '.config.chainId' > /data/chainid.txt;
            touch /data/genesis_init_done;
            echo "genesis init done";
          else
            echo "genesis is already initialized";
          fi;
          echo "bootnode init done: $(cat /data/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
  # Prysm
  lodestar:
    fullnameOverride: lodestar-nethermind-001
    enabled: true
    image:
      repository: g11tech/lodestar
      tag: devnet6-789f5
      pullPolicy: Always
    mode: "beacon"
    podLabels:
      network: 4844-devnet-6
      testnet: 4844-devnet-6
      ethereum_network: 4844-devnet-6
      ethereum_role: consensus
      consensus_client: lodestar
      execution_client: nethermind
      ethereum_instance: nethermind-lodestar-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    p2pNodePort:
      enabled: false
      startsAt: 31004
    persistence:
      enabled: true
      size: 50Gi
    extraArgs:
      - --execution.urls=http://nethermind-lodestar-001:8551
      - --checkpointSyncUrl=https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.bootnode-1.srv.4844-devnet-6.ethpandaops.io
      - --genesisStateFile=/data/testnet_spec/genesis.ssz
      - --paramsFile=/data/testnet_spec/config.yaml
      - --network.connectToDiscv5Bootnodes
      - --bootnodes="enr:-MS4QAJpvAJFBUZ2SdWXhw_eOOD43YYur7bk0wonV4C5dBYMAqN67AuMW6VG5iMzxcYblzMKcPGlBPL6NACimDJJJ5IJh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEP0jPUEhEBv__________gmlkgnY0gmlwhEDhR0eJc2VjcDI1NmsxoQO2Oy1oWO1nxDDm3tz2nrDv37kBHQsSzyZM9lkfB3qDNYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          DEPOSIT_CONTRACT_URI=https://config.4844-devnet-6.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.4844-devnet-6.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.4844-devnet-6.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.4844-devnet-6.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.4844-devnet-6.ethpandaops.io/cl/genesis.ssz;
          BOOTNODE_URI=https://config.4844-devnet-6.ethpandaops.io/bootstrap_nodes.txt;
          TRUSTED_SETUP_URI=https://config.4844-devnet-6.ethpandaops.io/trusted_setup.txt;
          mkdir -p /data/testnet_spec;
          if ! [ -f /data/testnet_spec/genesis.ssz ];
          then
            wget -O /data/testnet_spec/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/testnet_spec/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/testnet_spec/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/testnet_spec/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/testnet_spec/genesis.ssz $GENESIS_SSZ_URI;
            wget -O /data/testnet_spec/bootstrap_nodes.txt $BOOTNODE_URI;
            wget -O /data/testnet_spec/trusted_setup.txt $TRUSTED_SETUP_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          echo "bootnode init done: $(cat /data/testnet_spec/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
