# Ansible managed. Don't change this file manually. Template info: /roles/gen_kubernetes_config/templates/forky.yaml.j2,0f6d20a 2023/08/10 10:56

forky:
  fullnameOverride: forky
  replicas: 1
  image:
    repository: ethpandaops/forky
    tag: 0.0.34-debian
  resources:
    requests:
      cpu: 256m
      memory: 512Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: forky.dencun-devnet-8.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  config:
    listen_addr: ":5555"
    pprof_addr: ":6060"
    log_level: "debug"
    metrics:
      addr: ":9090"
      enabled: true
    forky:
      retention_period: "1m"
      store:
        type: memory
      indexer:
        dsn: "file::memory:?cache=shared"
        driver_name: sqlite
      ethereum:
        network:
          name: "dencun-devnet-8"
          spec:
            seconds_per_slot: 12
            slots_per_epoch: 32
            genesis_time: 1692182400
      sources:
        - name: bootnode-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.bootnode-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-ethereumjs-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: lighthouse-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: lodestar-ethereumjs-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: lodestar-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: lodestar-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: nimbus-ethereumjs-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: nimbus-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-geth-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: nimbus-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-ethereumjs-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.prysm-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.prysm-geth-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: prysm-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.prysm-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: teku-ethereumjs-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: teku-geth-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-geth-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
        - name: teku-nethermind-1
          type: "beacon_node"
          config:
            address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
            polling_interval: "12s"
