ethereumjs-lodestar-001-exe:
  fullnameOverride: ethereumjs-lodestar-001-exe
  image:
    repository: g11tech/ethereumjs
    tag: blobs-b6b63

  podLabels:
    network: 4844-devnet-5
    testnet: 4844-devnet-5
    ethereum_network: 4844-devnet-5
    ethereum_role: execution
    consensus_client: lodestar
    execution_client: ethereumjs
    ethereum_instance: ethereumjs-lodestar-001

  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi

  p2pNodePort:
    enabled: true
    port: 31220

  persistence:
    enabled: true
    size: 50Gi

  extraArgs:
  - --bootnodes="$(tr '\n' ',' < /data/bootnodes.txt)"
  - --gethGenesis=/data/genesis.json
  - --rpcAddr=0.0.0.0 
  - --rpcCors="*"
  - --rpc 
  - --rpcPort=8545
  - --rpcEngine
  - --rpcEngineAddr=0.0.0.0
  - --rpcEnginePort=8551
  - --ws
  - --wsAddr=0.0.0.0
  - --wsPort=8546
  - --wsEnginePort=8552

  initContainers:
  - name: init-genesis
    image: g11tech/ethereumjs:blobs-b6b63
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        BOOTNODE_URI=https://config.4844-devnet-5.ethpandaops.io/el/bootnodes;
        GENESIS_URI=https://config.4844-devnet-5.ethpandaops.io/el/genesis.json;
        if ! [ -f /data/genesis_init_done ];
        then
          wget -O /data/genesis.json $GENESIS_URI;
          wget -O /data/bootnodes.txt $BOOTNODE_URI;
          apk update && apk add jq;
          cat /data/genesis.json | jq -r '.config.chainId' > /data/chainid.txt;
          touch /data/genesis_init_done;
          echo "genesis init done";
        else
          echo "genesis is already initialized";
        fi;
        echo "bootnode init done: $(cat /data/bootnodes.txt)";
    volumeMounts:
      - name: storage
        mountPath: "/data"

ethereumjs-lodestar-001-con:
  fullnameOverride: ethereumjs-lodestar-001-con

  image:
    repository: ethpandaops/lodestar
    tag: eip4844-651ceeb
    pullPolicy: Always

  mode: "beacon"

  podLabels:
    network: 4844-devnet-5
    testnet: 4844-devnet-5
    ethereum_network: 4844-devnet-5
    ethereum_role: consensus
    consensus_client: lodestar
    execution_client: ethereumjs
    ethereum_instance: ethereumjs-lodestar-001

  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi

  p2pNodePort:
    enabled: false
    startsAt: 31004

  persistence:
    enabled: true
    size: 50Gi

  customCommand:
  - sh
  - -ac
  - >
    beacon
        --paramsFile=/data/testnet_spec/config.yaml
        --genesisStateFile=/data/testnet_spec/genesis.ssz
        --bootnodes="$(tr '\n' ',' < /data/testnet_spec/bootstrap_nodes.txt)"
        --network.connectToDiscv5Bootnodes
        --rest.port=4000
        --execution.urls=http://ethereumjs-lodestar-001-exe:8551
        --rest
        --rest.address=0.0.0.0
        --rest.cors="*"
        --enr.ip=$(POD_IP)
        --metrics
        --rest.namespace *
        --enr.udp 9000
        --metrics.port=8080
        --eth1.depositContractDeployBlock=0
        --jwt-secret="/data/jwt.hex"

  initContainers:
  - name: init-genesis
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        DEPOSIT_CONTRACT_URI=https://config.4844-devnet-5.ethpandaops.io/deposit_contract.txt;
        DEPOSIT_CONTRACT_BLOCK_URI=https://config.4844-devnet-5.ethpandaops.io/cl/deposit_contract_block.txt;
        DEPLOY_BLOCK_URI=https://config.4844-devnet-5.ethpandaops.io/cl/deploy_block.txt;
        GENESIS_CONFIG_URI=https://config.4844-devnet-5.ethpandaops.io/cl/config.yaml;
        GENESIS_SSZ_URI=https://config.4844-devnet-5.ethpandaops.io/cl/genesis.ssz;
        BOOTNODE_URI=https://config.4844-devnet-5.ethpandaops.io/bootstrap_nodes.txt;
        mkdir -p /data/testnet_spec;
        if ! [ -f /data/testnet_spec/genesis.ssz ];
        then
          wget -O /data/testnet_spec/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
          wget -O /data/testnet_spec/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
          wget -O /data/testnet_spec/deploy_block.txt $DEPLOY_BLOCK_URI;
          wget -O /data/testnet_spec/config.yaml $GENESIS_CONFIG_URI;
          wget -O /data/testnet_spec/genesis.ssz $GENESIS_SSZ_URI;
          wget -O /data/testnet_spec/bootstrap_nodes.txt $BOOTNODE_URI;
          echo "genesis init done";
        else
          echo "genesis exists. skipping...";
        fi;
        echo "bootnode init done: $(cat /data/testnet_spec/bootstrap_nodes.txt)";
    volumeMounts:
      - name: storage
        mountPath: "/data"