name: Install deps
description: Install deps
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install asdf
      uses: asdf-vm/actions/setup@v2

    - name: Install asdf tools
      run: ./asdf-setup.sh
