# role: ethpandaops.general.ethereum_node
ethereum_node_cl: lighthouse

# role: ethpandaops.general.lighthouse
lighthouse_container_image: sigp/lighthouse:latest
lighthouse_container_command_extra_args: []
lighthouse_validator_container_command_extra_args: []
