default_ethereum_client_images:
### Consensus layer clients
  lighthouse: sigp/lighthouse:deneb-modern # :heavy_check_mark:
  lodestar: chainsafe/lodestar:next # :heavy_check_mark:
  nimbus: ethpandaops/nimbus:unstable-29dbab9 # :heavy_check_mark:
  prysm: ethpandaops/prysm:devnet8-fix-c728e09 # :heavy_check_mark:
  prysm_validator: ethpandaops/prysm-validator:devnet8-fix-c728e09 # :exclamation:
  teku: consensys/teku:develop # :heavy_check_mark:
### Execution layer clients
  besu: ethpandaops/besu:main-139fc12 # :heavy_check_mark:
  geth: ethpandaops/geth:lightclient-devnet-8-edf4ab3 # :heavy_check_mark:
  erigon: ethpandaops/erigon:devel-75e3ae0 # :exclamation:
  ethereumjs: ethpandaops/ethereumjs:master-35ec012 # :heavy_check_mark:
  nethermind: nethermindeth/nethermind:cancun-4a540fc # :heavy_check_mark:
  reth: ethpandaops/reth:main # :exclamation:


default_tooling_images:
  xatu_sentry: ethpandaops/xatu:0.0.60
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:0.21.0
  tx_fuzz: ethpandaops/tx-fuzz:1.1.0
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:0.0.34-debian
  fauceth: skylenet/fauceth:fix_fee_estimation
  ethstats: skylenet/ethstats-server:poa-no-geoip
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:0.0.10-dencun-debian
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  light_beaconchain_explorer: pk910/light-beaconchain-explorer:unstable
