ethereum_cl_bootnodes:
  - "{{ hostvars['bootnode-1']['cl_bootnode_fact_enr'] }}"
  - "{{ hostvars['bootnode-1']['ethereum_node_fact_cl_enr'] }}"
  - "enr:-Ly4QJ4C2KCGx8Fxw1xWHs9kvuJZaZI6nlIdDuTCwsEwk1ZZRteCXYo00qzS8K82bUyCubrEcdmxKx-cBIAGZWN1ZjABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpChikUGUAAAABQAAAAAAAAAgmlkgnY0gmlwhEDhSYuJc2VjcDI1NmsxoQJCIgAt7fhrrBbwO-JGjD2VZluZd7-8P_9g0h2tWq-kHIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "{{ hostvars['teku-geth-1']['ethereum_node_fact_cl_enr'] }}"
  - "{{ hostvars['lighthouse-geth-1']['ethereum_node_fact_cl_enr'] }}"
ethereum_el_bootnodes: 
  - "{{ hostvars['bootnode-1']['ethereum_node_fact_el_enode'] }}"
  - "enode://ae6ce36c3684d3d12b6aa26e3c231ced50ea238e40ea12fe89ee8691f22198144cfc5a4fccbf4b60439783966c9ccfcba88f8b8fe1ef3a42738a405b992ba32d@64.225.73.139:30303"
  - "{{ hostvars['teku-geth-1']['ethereum_node_fact_el_enode'] }}"
  - "{{ hostvars['lighthouse-geth-1']['ethereum_node_fact_el_enode'] }}"

# role: ethpandaops.general.prometheus
prometheus_remote_push_url: https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write
prometheus_remote_write_username: "{{ secret_prometheus_remote_write.username }}"
prometheus_remote_write_password: "{{ secret_prometheus_remote_write.password }}"
prometheus_config: |
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
      instance: "{{ inventory_hostname }}"
      ip_address: "{{ ansible_host }}"
      network: "{{ ethereum_network_name }}"
      testnet: "{{ ethereum_network_name }}"
      execution_client: "{{ ethereum_node_el }}"
      consensus_client: "{{ ethereum_node_cl }}"
  remote_write:
    - queue_config:
        batch_send_deadline: 5s
        max_backoff: 500ms
        max_samples_per_send: 500
        min_backoff: 50ms
        max_shards: 100
      url: {{ prometheus_remote_push_url }}
      remote_timeout: 10s
      basic_auth:
        username: {{ prometheus_remote_write_username }}
        password: {{ prometheus_remote_write_password }}
  scrape_configs:
    - job_name: "prometheus"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["172.17.0.1:9100"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["ethereum-metrics-exporter:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "consensus_node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["{{ vars[ethereum_node_cl + '_container_name'] }}:{{ ethereum_node_cl_ports_metrics }}"]
          labels:
            instance: "{{ inventory_hostname }}"
