# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/light-beaconchain-explorer.yaml.j2

light-beaconchain-explorer:
  fullnameOverride: light-beaconchain-explorer
  image:
    repository: pk910/light-beaconchain-explorer
    tag: unstable
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: light-beaconchain-explorer.dencun-devnet-8.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.bootnode-1.srv.dencun-devnet-8.ethpandaops.io
    name: bootnode-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-nethermind-1


  name:  "dencun-devnet-8"
  configPath: "https://config.dencun-devnet-8.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.dencun-devnet-8.ethpandaops.io/api/v1/nodes/validator-ranges"

  config: |
    logging:
      outputLevel: "info"
      #outputStderr: false

      #filePath: "explorer.log"
      #fileLevel: "warn"

    # Chain network configuration
    chain:
      # use built in config by name ("mainnet", "prater", "sepolia")
      name: "{{ .Values.name }}"
      configPath: "{{ .Values.configPath }}"
      displayName: "{{ .Values.name }}"

    # HTTP Server configuration
    server:
      host: "0.0.0.0" # Address to listen on
      port: "{{ .Values.httpPort }}" # Port to listen on

    frontend:
      enabled: true # Enable or disable to web frontend
      debug: false
      minimize: false # minimize html templates

      # Name of the site, displayed in the title tag
      siteName: "Light Beaconchain Explorer"
      siteSubtitle: "{{ .Release.Name }}"

      # link to EL Explorer
      ethExplorerLink: "{{ .Values.ethExplorerLink }}"

      # file or inventory url to load validator names from
      validatorNamesYaml: "/data/ranges.yaml"
      validatorNamesInventory: "{{ .Values.validatorNamesInventory }}"

    beaconapi:
      # CL Client RPC
      endpoints:
        {{- range .Values.endpoints }}
          url: {{ .url | quote }}
          {{- if .name }}
          name: {{ .name | quote }}
          {{- end }}
          {{- if .priority }}
          priority: {{ .priority | quote }}
          {{- end }}
          {{- if .archive }}
          archive: {{ .archive | quote }}
          {{- end }}
          {{- if .headers }}
          headers:
          {{- range $key, $value := .headers }}
            {{ $key | quote | default "" }}: {{ $value | quote | default ""}}
          {{- end }}
          {{- end }}
        {{- end }}

      # local cache for page models
      localCacheSize: 100 # 100MB

      # remote cache for page models
      redisCacheAddr: ""
      redisCachePrefix: ""

    # indexer keeps track of the latest epochs in memory.
    indexer:
      # number of epochs to load on startup
      prepopulateEpochs: 2

      # max number of epochs to keep in memory
      inMemoryEpochs: 3

      # epoch processing delay (should be >= 2)
      epochProcessingDelay: 2

      # disable synchronizing and everything that writes to the db (indexer just maintains local cache)
      disableIndexWriter: false

      # number of seconds to wait between each epoch (don't overload CL client)
      syncEpochCooldown: 2

    database:
      engine: "pgsql"
      pgsql:
        host: "{{ include "light-beaconchain-explorer.fullname" $ }}-postgresql"
        port: 5432
        user: "{{ .Values.postgresql.auth.username }}"
        password: "{{ .Values.postgresql.auth.password }}"
        name: "{{ .Values.postgresql.auth.database }}"


  postgresql:
    fullnameOverride: light-beaconchain-explorer-postgresql
