# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/light-beaconchain-explorer.yaml.j2

light-beaconchain-explorer:
  fullnameOverride: light-beaconchain-explorer
  image:
    repository: pk910/light-beaconchain-explorer
    tag: unstable
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: light-beaconchain-explorer.dencun-devnet-8.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.bootnode-1.srv.dencun-devnet-8.ethpandaops.io
    name: bootnode-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: lighthouse-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.lodestar-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: lodestar-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.nimbus-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: nimbus-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: prysm-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-besu-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-besu-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-erigon-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-erigon-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-ethereumjs-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-ethereumjs-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-geth-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.teku-nethermind-1.srv.dencun-devnet-8.ethpandaops.io
    name: teku-nethermind-1

  config:
    name: dencun-devnet-8
    configPath: "https://config.dencun-devnet-8.ethpandaops.io/cl/config.yaml"
    validatorNamesInventory: "https://config.dencun-devnet-8.ethpandaops.io/api/v1/nodes/validator-ranges"