default_ethereum_client_images:
### Consensus layer clients
  lighthouse: ethpandaops/lighthouse:unstable-c55608b
  lodestar: ethpandaops/lodestar:unstable-9262064
  nimbus: ethpandaops/nimbus:unstable-f125a5c
  prysm: gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-374d77
  prysm_validator: gcr.io/prysmaticlabs/prysm/validator:HEAD-374d77
  teku: ethpandaops/teku:master-f733b7c

### Execution layer clients
  besu: ethpandaops/besu:main-80c8a8f
  geth: ethpandaops/geth:master-cd58897
  erigon: ethpandaops/erigon:devel-33fc53f
  ethereumjs: ethpandaops/ethereumjs:master-c5054eb
  nethermind: nethermindeth/nethermind:release-1.25.0
  reth: ethpandaops/reth:main-b1d0dc4
