blobscan:
  fullnameOverride: blobscan
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: blobscan.4844-devnet-7.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blobscan
                port:
                  number: 3000
  blobscandb:
    fullnameOverride: blobscan-blobscandb

blobscan-indexer:
  fullnameOverride: blobscan-indexer
  image:
    tag: latest
  extraEnv:
    - name: SECRET_KEY
      value: "supersecret"
    - name: BLOBSCAN_API_ENDPOINT
      value: "http://blobscan-api:3001"
    - name: EXECUTION_NODE_ENDPOINT
      value: http://nethermind-lodestar-001:8545
    - name: BEACON_NODE_ENDPOINT
      value: http://lodestar-nethermind-001:5052
  
  # Fake google cloud server
  initContainers:
  - name: fake-gcs-server
    image: fsouza/fake-gcs-server
    imagePullPolicy: IfNotPresent
    command: ["-scheme", "http"]
    volumeMounts:
      - name: storage
        mountPath: /storage
  
  extraVolumes:
    - name: storage
      emptyDir: {}

# Blobscan API
blobscan-api:
  fullnameOverride: blobscan-api
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: blobscan-api.4844-devnet-7.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blobscan-api
                port:
                  number: 3001
