testnet-homepage:
  fullnameOverride: homepage

  replicas: 1

  image:
    pullPolicy: Always
    repository: ethpandaops/ethereum-testnet-homepage

  resources:
    requests:
      cpu: 33m
      memory: 64Mi
  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: 4844-devnet-5.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  customMarkdown: |-
    ## General information
    ### Key split
    ```
    0-9000 - EthPandaOps
    9000-9500 - EthPandsOps
    9500 - 10000 - Client Teams (50 per team) - Contact EF DevOps if you want to run a validator!
    ```
    
    ## Network Spec
    https://hackmd.io/@inphi/HJZo4vQGn#

    ## Ansible setup
    https://github.com/ethpandaops/4844-testnet

    ## Client versions
    https://notes.ethereum.org/@samcm/4844-devnet-5

    enode for execution clients:
    ```sh
    ```

    enr for consensus clients:
    ```sh
    ```



    ## Genesis configuration
    ### Execution layer clients
    ```sh
    https://config.4844-devnet-5.ethpandaops.io/el/bootnodes
    https://config.4844-devnet-5.ethpandaops.io/el/genesis.json
    https://config.4844-devnet-5.ethpandaops.io/el/chainspec.json
    ```
    ### Consensus layer clients
    ```sh
    https://config.4844-devnet-5.ethpandaops.io/cl/bootnodes
    https://config.4844-devnet-5.ethpandaops.io/cl/config.yaml
    https://config.4844-devnet-5.ethpandaops.io/cl/genesis.ssz
    https://config.4844-devnet-5.ethpandaops.io/cl/deploy_block.txt
    https://config.4844-devnet-5.ethpandaops.io/cl/deposit_contract.txt
    https://config.4844-devnet-5.ethpandaops.io/cl/deposit_contract_block.txt
    ```
    



  customArgs:
    - -b
    - https://4844-devnet-5.ethpandaops.io

  config:
    baseURL: https://4844-devnet-5.ethpandaops.io
    languageCode: en-us
    title: 4844-devnet-5
    theme: PaperMod
    markup:
      highlight:
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: monokai
    params:
      disableThemeToggle: true
      defaultTheme: dark
      ethereum:
        faucetUrl: https://faucet.4844-devnet-5.ethpandaops.io
        faucet2Url: https://faucet-2.4844-devnet-5.ethpandaops.io
        rpcUrl: https://rpc.4844-devnet-5.ethpandaops.io
        explorerUrl: https://explorer.4844-devnet-5.ethpandaops.io
        forkmonUrl: https://forkmon.4844-devnet-5.ethpandaops.io
        beaconexplorerUrl: https://beaconchain.4844-devnet-5.ethpandaops.io
        checkpointSyncUrl: https://checkpoint-sync.4844-devnet-5.ethpandaops.io
        blobscanUrl: https://blobscan.4844-devnet-5.ethpandaops.io
        ethstatsUrl: https://ethstats.4844-devnet-5.ethpandaops.io
        chainName: "4844-devnet-5"
        chainId: "4844001004"
        github: https://github.com/ethpandaops/4844-testnet/tree/master/network-configs/devnet-5
      metamask:
        enabled: true
      logo:
        enabled: false
        url: https://i.imgur.com/M0gEdpw.png
      assets:
        favicon: https://i.imgur.com/M0gEdpw.png
        favicon16x16: https://i.imgur.com/M0gEdpw.png
        favicon32x32: https://i.imgur.com/M0gEdpw.png
        apple_touch_icon: https://i.imgur.com/M0gEdpw.png
        safari_pinned_tab: https://i.imgur.com/M0gEdpw.png

      links:
      - name: "Testnet Spec"
        dataLookup: github
      - name: "JSON RPC"
        dataLookup: rpcUrl
      - name: "Explorer"
        dataLookup: explorerUrl
      # - name: "Beaconchain explorer"
      #   dataLookup: beaconexplorerUrl
      # - name: "Transaction explorer"
      #   dataLookup: explorerUrl
      # - name: "Checkpoint Sync"
      #   dataLookup: checkpointSyncUrl
      - name: "Faucet 1"
        dataLookup: faucetUrl
      - name: "Faucet 2"
        dataLookup: faucet2Url  
      - name: "Forkmon"
        dataLookup: forkmonUrl
      - name: "Blobscan"
        dataLookup: blobscanUrl
      - name: "Ethstats"
        dataLookup: ethstatsUrl
    menu:
      main:
        - identifier: ethereum-website
          name: ethereum.org
          url: https://ethereum.org
          weight: 30
    disableKinds: ["taxonomy", "taxonomyTerm"]
    copyright: "This page is "
