teku_container_command_extra_args:
  - --network=/network-config/config.yaml
  - --p2p-discovery-bootnodes={{ ethereum_cl_bootnodes | join(',') }}
  - --p2p-peer-upper-bound=100
  - --data-storage-non-canonical-blocks-enabled=true
  - --data-storage-mode=PRUNE
  - --validators-graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
  - --logging=info
  - --Xlog-include-p2p-warnings-enabled
  - --metrics-block-timing-tracking-enabled
  - --Xmetrics-blob-sidecars-storage-enabled=true
  - --Xtrusted-setup=/network-config/trusted_setup.txt
  - --initial-state=https://{{secret_nginx_shared_basic_auth.name}}:{{secret_nginx_shared_basic_auth.password}}@bn.teku-nethermind-1.srv.4844-devnet-6.ethpandaops.io/eth/v2/debug/beacon/states/finalized