# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/Chart.yaml.j2

apiVersion: v2
name: dugtrio
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: dugtrio
    repository: file:///home/pk910/github/ethpandaops/ethereum-helm-charts/charts/dugtrio
    version: 0.0.1
