# Ansible managed. Don't change this file manually. Template info: /roles/gen_kubernetes_config/templates/ethstats.yaml.j2,49f27d5 2023/07/18 13:12$

ethstats:
  fullnameOverride: ethstats

  image:
    repository: skylenet/ethstats-server
    tag: poa-no-geoip

  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: ethstats.4844-devnet-7.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  secretEnv:
    WS_SECRET: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.ethstats_secret}>"

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
