- name: Generate Chart.yaml
  ansible.builtin.template:
    src: Chart.yaml.j2
    dest: "{{ default_dir }}/{{ chart_item.key | replace('_', '-') }}/Chart.yaml"
    mode: "0644"
  loop: "{{ helm_charts | dict2items }}"
  loop_control:
    loop_var: chart_item

# - name: Check if dependencies are required
#   ansible.builtin.stat:
#     path: "{{ default_dir }}/{{ chart_item.key | replace('_', '-') }}/charts/{{ chart_item.key | replace('_', '-') }}-{{ chart_item.value }}"
#   loop: "{{ helm_charts | dict2items }}"
#   loop_control:
#     loop_var: chart_item
#   register: dependencies_required


# - name: Run helm dependency build
#   ansible.builtin.command: helm dependency build "{{ default_dir }}/{{ item.key | replace('_', '-') }}"
#   loop: "{{ helm_charts | dict2items }}"
#   loop_control:
#     loop_var: item
#   when: dependencies_required and not (item.key | replace('_', '-') == item.value)

- name: Copy the helm ignore file
  ansible.builtin.copy:
    src: ".helmignore"
    dest: "{{ default_dir }}/{{ item.key | replace('_', '-') }}/.helmignore"
    mode: "0644"
  loop: "{{ helm_charts | dict2items }}"
