- name: Inform which chart is being processed
  ansible.builtin.debug:
    msg: "Generating '{{ item.key }}' with template '{{ item.value.valuesTemplatePath | default('') }}'"

- name: Create directory
  ansible.builtin.file:
    path: "{{ gen_kubernetes_config_default_output_dir }}/{{ item.key }}"
    state: directory
    mode: "0755"

- name: Generate Chart.yaml
  ansible.builtin.template:
    src: Chart.yaml.j2
    dest: "{{ gen_kubernetes_config_default_output_dir }}/{{ item.key }}/Chart.yaml"
    mode: "0644"

- name: Copy the helm ignore file
  ansible.builtin.copy:
    src: ".helmignore"
    dest: "{{ gen_kubernetes_config_default_output_dir }}/{{ item.key }}/.helmignore"
    mode: "0644"

- name: Add ethpandaops helm repository
  kubernetes.core.helm_repository:
    name: ethereum-helm-charts
    url: https://ethpandaops.github.io/ethereum-helm-charts
    state: present

- name: Add blobscan helm repository
  kubernetes.core.helm_repository:
    name: blobscan-helm-charts
    url: https://blobscan.github.io/blobscan-helm-charts/
    state: present

- name: Check if dependencies should be updated
  ansible.builtin.command:
    cmd: >-
      ls
      {% for d in item.value.dependencies | default([]) %}
      {{ gen_kubernetes_config_default_output_dir }}/{{ item.key }}/charts/{{ d.name }}-{{ d.version }}.tgz
      {% endfor %}
  changed_when: false
  failed_when: false
  register: chart_needs_update

- name: Run helm dependency update
  ansible.builtin.command: # noqa: no-changed-when
    cmd: helm  dependency update {{ gen_kubernetes_config_default_output_dir }}/{{ item.key }}
  when: chart_needs_update.rc != 0

- name: Run helm dependency build
  ansible.builtin.command: # noqa: no-changed-when
    cmd: helm dependency build {{ gen_kubernetes_config_default_output_dir }}/{{ item.key }}
  when: chart_needs_update.rc != 0

- name: Include client vars
  ansible.builtin.include_vars:
    dir: "{{ inventory_dir }}/group_vars"

- name: Generate values file
  ansible.builtin.template:
    src: "{{ item.value.valuesTemplatePath }}"
    dest: "{{ gen_kubernetes_config_default_output_dir }}/{{ item.key }}/values.yaml"
    mode: "0644"
