lodestar_validator_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
  - --useProduceBlockV3
  - --builder.selection=builderonly
