teku_container_validator_args:
  - --validators-external-signer-url=http://web3signer:9000
  - --validators-proposer-default-fee-recipient={{ teku_validator_fee_recipient }}
  - --validators-keystore-locking-enabled=false
