lighthouse_container_command_extra_args:
  - --testnet-dir=/network-config
  - --boot-nodes={{ ethereum_cl_bootnodes | join(',') }}
  - --self-limiter=blob_sidecars_by_range:256/10
  - --debug-level={{ log_level | default('debug') }}
  - --builder=http://mev-boost:18550

lighthouse_validator_container_command_extra_args:
  - --testnet-dir=/network-config
  - --graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
  - --builder-proposals
