nimbus_container_command_extra_simple_args:
  - --network=/network-config
  - --validator-monitor-auto=false
  - --doppelganger-detection=off
  - --log-level={{ log_level | upper | default('DEBUG') }}
  - --light-client-data-serve=false
  - --graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
  - --payload-builder=true
  - --payload-builder-url=http://mev-boost:18550
