ethereumjs_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
  DEBUG: ethjs,client:*
ethereumjs_container_command_extra_args:
  - --gethGenesis=/network-config/genesis.json
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --sync=full
  - --maxPeers=10
  - --maxPerRequest=10
  - --isSingleNode=true
  - --logLevel={{ log_level | default('debug') }}
