apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
- name: forky
  repository: https://ethpandaops.github.io/ethereum-helm-charts
  version: 0.1.1
