
goomy_container_networks: "{{ docker_networks_shared }}"
goomy_rpc_urls:
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-geth-10.{{ network_subdomain }}"
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-geth-11.{{ network_subdomain }}"
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-geth-12.{{ network_subdomain }}"
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-geth-13.{{ network_subdomain }}"
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-nethermind-1.{{ network_subdomain }}"
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-besu-1.{{ network_subdomain }}"
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-reth-1.{{ network_subdomain }}"

goomy_scenario: "combined"
goomy_extra_args: ["--sidecars", "1", "--throughput", "5", "--max-pending", "50"]
