# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - g11tech
  - acolytec3
  - holgerd77
  - jochem-brouwer

# role: ethpandaops.general.ethereum_node
ethereum_node_el: ethereumjs

# role: ethpandaops.general.ethereumjs
ethereumjs_container_image: g11tech/ethereumjs:jan25@sha256:f126141c234da7eeeb233d0bb0cedea8a2f06a822f2178f222aca6718478db6e
ethereumjs_ports_http_rpc: 8545
ethereumjs_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereumjs_ports_http_rpc }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
ethereumjs_container_volumes:
  - "{{ ethereumjs_datadir }}:/data"
  - "{{ ethereumjs_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ ethereum_network_config_dir }}:/network-config:ro"
ethereumjs_container_command_extra_args:
  - --gethGenesis=/network-config/genesis.json
  - --bootnodes={{ ethereum_el_bootnode }}
  - --syncMode=full
  - --maxPeers=75

# role: ethpandaops.general.ethereum_metrics_exporter
ethereum_metrics_exporter_el_endpoint: http://ethereumjs:8545
