# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - mariusVanDerWijden
  - holiman
  - karalabe
  - g11tech

# role: ethpandaops.general.ethereum_node
ethereum_node_el: geth

# role: ethpandaops.general.geth
geth_container_image: ethpandaops/geth:mdehoog-eip4844-20d3ce8
geth_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
geth_container_command_extra_args:
  - "--syncmode=full"
  - "--bootnodes={{ ethereum_el_bootnode }}"
  - "--ethstats={{ inventory_hostname }}:{{ ethstats_secret }}@{{ ethstats_url }}"
geth_init_custom_network: true
geth_init_custom_network_genesis_file: "{{ ethereum_network_config_dir }}/genesis.json"
