- name: Install dependencies
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: passlib

- name: Generate htpasswd files for nginx auth
  community.general.htpasswd:
    path: "{{ item }}"
    name: "{{ gen_basic_auth_nginx_name }}"
    password: "{{ gen_basic_auth_nginx_password }}"
  loop: "{{ gen_basic_auth_nginx_paths }}"
