# Ansible managed. Don't change this file manually. Template info: /roles/gen_kubernetes_config/templates/ethereum-node.yaml.j2,a3df7b9 2023/07/19 17:20

node-001:
  global:
    main:
      network: dencun-devnet-8
    checkpointSync:
      enabled: false
      addresses:
        dencun-devnet-8: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-geth-1.srv.dencun-devnet-8.ethpandaops.io
  nethermind:
    fullnameOverride: nethermind-teku-001
    enabled: true
    image:
      repository: nethermindeth/nethermind
      tag: eip-4844-v6-36
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 50Gi
    podLabels:
      network: dencun-devnet-8
      testnet: dencun-devnet-8
      ethereum_network: dencun-devnet-8
      ethereum_role: execution
      consensus_client: teku
      execution_client: nethermind
      ethereum_instance: nethermind-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    extraArgs:
      - --Discovery.Bootnodes="$(tr '\n' ',' < /data/bootnodes.txt)"
      - --Init.ChainSpecPath=/data/genesis.json
      - --config=none.cfg
      - --Init.IsMining=false
      - --Pruning.Mode=None
      - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
      - --EthStats.Enabled=true
      - --EthStats.Name=k8s-nethermind-teku-001
      - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>
      - --EthStats.Server=wss://ethstats.dencun-devnet-8.ethpandaops.io
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          GENESIS_URI=https://config.dencun-devnet-8.ethpandaops.io/el/chainspec.json;
          TRUSTED_SETUP_URI=https://config.dencun-devnet-8.ethpandaops.io/trusted_setup.txt;
          if ! [ -f /data/genesis_init_done ];
          then
            apk update && apk add curl jq;
            wget -O /data/genesis.json $GENESIS_URI;
            curl -s https://config.dencun-devnet-8.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .execution.enode' > /data/bootnodes.txt;
            wget -O /data/trusted_setup.txt $TRUSTED_SETUP_URI;
            cat /data/genesis.json | jq -r '.config.chainId' > /data/chainid.txt;
            touch /data/genesis_init_done;
            echo "genesis init done";
          else
            echo "genesis is already initialized";
          fi;
          echo "bootnode init done: $(cat /data/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"

  teku:
    fullnameOverride: teku-nethermind-001
    enabled: true
    image:
      repository: consensys/teku
      tag: 23.6.1
      pullPolicy: Always
    mode: "beacon"
    podLabels:
      network: dencun-devnet-8
      testnet: dencun-devnet-8
      ethereum_network: dencun-devnet-8
      ethereum_role: consensus
      consensus_client: teku
      execution_client: nethermind
      ethereum_instance: nethermind-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 50Gi
    extraArgs:
      - --network=/data/testnet_spec/config.yaml
      - --initial-state=/data/testnet_spec/genesis.ssz
      - --p2p-discovery-bootnodes=ADD_BOOTNODES_HERE
      - --p2p-peer-upper-bound=100
      - --data-storage-non-canonical-blocks-enabled=true
      - --data-storage-mode=PRUNE
      - --logging=info
      - --Xlog-include-p2p-warnings-enabled
      - --metrics-block-timing-tracking-enabled
      - --Xmetrics-blob-sidecars-storage-enabled=true
      - --Xtrusted-setup=/data/testnet_spec/trusted_setup.txt
      - --Xpeer-rate-limit=100000
      - --Xpeer-request-limit=1000
      - --Xepochs-store-blobs=max # Keep blobs forever
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.dencun-devnet-8.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.dencun-devnet-8.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.dencun-devnet-8.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.dencun-devnet-8.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.dencun-devnet-8.ethpandaops.io/cl/genesis.ssz;
          curl -s https://config.dencun-devnet-8.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/bootnodes.txt;
          TRUSTED_SETUP_URI=https://config.dencun-devnet-8.ethpandaops.io/trusted_setup.txt;
          mkdir -p /data/testnet_spec;
          if ! [ -f /data/testnet_spec/genesis.ssz ];
          then
            wget -O /data/testnet_spec/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/testnet_spec/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/testnet_spec/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/testnet_spec/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/testnet_spec/genesis.ssz $GENESIS_SSZ_URI;
            wget -O /data/testnet_spec/trusted_setup.txt $TRUSTED_SETUP_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/bootnodes.txt | sed 's/[^,]*/"&"/g') > /data/bootnodes2.txt;
          mv /data/bootnodes2.txt /data/bootnodes.txt;
          echo "bootnode init done: $(cat /data/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
