- hosts: all
  serial: "{{ batch_count | default('100%') }}"
  become: true
  tasks:
    - name: Remove eth containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        # Execution layer clients
        - "besu"
        - "erigon-init"
        - "erigon"
        - "ethereumjs"
        - "geth-init"
        - "geth"
        - "nethermind"
        # Consensus layer clients
        - "lighthouse-validator"
        - "lighthouse"
        - "lodestar-validator"
        - "lodestar"
        - "nimbus"
        - "prysm-validator"
        - "prysm"
        - "teku-validator"
        - "teku"
        # Others
        - "ethereum-metrics-exporter"
    - name: Remove data dirs
      file:
        state: absent
        path: "{{ item }}"
      loop:
        # Execution layer data
        - /data/besu
        - /data/erigon
        - /data/ethereumjs
        - /data/geth
        - /data/nethermind
        # Consensus layer data
        - /data/lighthouse
        - /data/lighthouse-validator
        - /data/lodestar
        - /data/lodestar-validator
        - /data/nimbus
        - /data/prysm
        - /data/prysm-validator
        - /data/teku
        - /data/teku-validator
        # Config files
        - /data/ethereum-network-config
        - /data/execution-auth.secret
