- import_playbook: ethpandaops.general.bootstrap_server
  tags: [bootstrap]

- hosts: all
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    - role: robertdebock.fail2ban
      tags: [fail2ban]
    - role: geerlingguy.docker
      tags: [docker]
    - role: geerlingguy.pip
      pip_install_packages:
        - name: docker
        - name: docker-compose
      tags: [pip]
    - role: ethpandaops.general.docker_cleanup
      tags: [docker_cleanup]
    - role: ethpandaops.general.docker_network
      tags: [docker_network]
    - role: nickhammond.logrotate
      tags: [logrotate]
    - role: ethpandaops.general.node_exporter
      tags: [node_exporter]
    - role: ethpandaops.general.prometheus
      tags: [prometheus]

- hosts: ethereum_node
  become: true
  roles:
    - role: eth_testnet_config
      tags: [eth_testnet_config]
    - role: validator_keys
      tags: [validator_keys]
    - role: ethpandaops.general.ethereum_node
      tags: [ethereum_node]
    - role: ethpandaops.general.ethereum_metrics_exporter
      tags: [ethereum_metrics_exporter]
    - role: ethpandaops.general.docker_nginx_proxy
      tags: [docker_nginx_proxy]
    - role: gen_basic_auth_nginx
      tags: [docker_nginx_proxy]
