apiVersion: batch/v1
kind: CronJob
metadata:
  name: enode-job
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: enode
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - >
              apk update -q && apk add -q --no-cache curl jq
              /usr/bin/jq .result.enode > /config/enode.txt << EOF
              $(curl -s -u $COMBINED --data '{"method":"admin_nodeInfo","params":[],"id":1,"jsonrpc":"2.0"}' \
                -H "Content-Type: application/json"  -X POST \
                https://rpc.prysm-nethermind-1.srv.4844-devnet-5.ethpandaops.io)
              EOF
            volumeMounts:
              - name: config
                mountPath: /config
            env: 
              - name: COMBINED
                valueFrom:
                  secretKeyRef:
                    name: nginxlogin
                    key: combined
          volumes:
            - name: config
              emptyDir: {}
            - name: secrets
              secret:
                secretName: nginxlogin
          restartPolicy: OnFailure
