{{- if .Values.config.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: github-external
spec:
  type: ExternalName
  externalName: raw.githubusercontent.com

---
{{- range .Values.config.files }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-config-{{ .path | replace "/" "-" | replace "." "-" | replace "_" "-" | lower }}
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-public
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .upstream }}"
    nginx.ingress.kubernetes.io/rewrite-target: "{{ .target }}"
spec:
  rules:
  - host: "config.{{ $.Values.domain }}"
    http:
      paths:
      - path: {{ .path }}
        pathType: Exact
        backend:
          service:
            name: github-external
            port:
              number: 443
---
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx-web
---
{{- range .Values.local }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-config-enrtxt
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-public
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: "config.{{ $.Values.domain }}"
    http:
      paths:
      - path: {{ .path }}
        pathType: Exact
        backend:
          service: 
            name: nginx-web-service
            port:
              number: 80
{{- end }}