forkmon:
  fullnameOverride: forkmon
  image: 
    repository: holiman/nodemonitor
    tag: latest@sha256:5cd609761065b8b1d7d6e91cc11725df94188d939378ef3aa97fbf68fe006374
  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: forkmon.4844-devnet-6.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  network: 4844-devnet-6
  endpoints:
  # Rpc
  - addr: http://geth-prysm-001:8545
    name: rpc-geth-prysm

  # # Prysm
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-ethereumjs-1.srv.4844-devnet-6.ethpandaops.io
  #   name: prysm-ethereumjs-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.srv.4844-devnet-6.ethpandaops.io
  #   name: prysm-nethermind-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-erigon-1.srv.4844-devnet-6.ethpandaops.io
  #   name: prysm-erigon-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-geth-1.srv.4844-devnet-6.ethpandaops.io
  #   name: prysm-geth-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-besu-1.srv.4844-devnet-6.ethpandaops.io
  #   name: prysm-besu-1
  # # Lighthouse
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-ethereumjs-1.srv.4844-devnet-6.ethpandaops.io
  #   name: lighthouse-ethereumjs-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.srv.4844-devnet-6.ethpandaops.io
  #   name: lighthouse-nethermind-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-erigon-1.srv.4844-devnet-6.ethpandaops.io
  #   name: lighthouse-erigon-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.srv.4844-devnet-6.ethpandaops.io
  #   name: lighthouse-geth-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-besu-1.srv.4844-devnet-6.ethpandaops.io
  #   name: lighthouse-besu-1
  # Lodestar
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-ethereumjs-1.srv.4844-devnet-6.ethpandaops.io
    name: lodestar-ethereumjs-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-nethermind-1.srv.4844-devnet-6.ethpandaops.io
    name: lodestar-nethermind-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-erigon-1.srv.4844-devnet-6.ethpandaops.io
  #   name: lodestar-erigon-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-geth-1.srv.4844-devnet-6.ethpandaops.io
    name: lodestar-geth-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-besu-1.srv.4844-devnet-6.ethpandaops.io
    name: lodestar-besu-1
  # Teku
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-ethereumjs-1.srv.4844-devnet-6.ethpandaops.io
    name: teku-ethereumjs-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-nethermind-1.srv.4844-devnet-6.ethpandaops.io
    name: teku-nethermind-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-erigon-1.srv.4844-devnet-6.ethpandaops.io
  #   name: teku-erigon-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-geth-1.srv.4844-devnet-6.ethpandaops.io
    name: teku-geth-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-besu-1.srv.4844-devnet-6.ethpandaops.io
    name: teku-besu-1
  # # Nimbus
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.nimbus-ethereumjs-1.srv.4844-devnet-6.ethpandaops.io
  #   name: nimbus-ethereumjs-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.nimbus-nethermind-1.srv.4844-devnet-6.ethpandaops.io
  #   name: nimbus-nethermind-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.nimbus-erigon-1.srv.4844-devnet-6.ethpandaops.io
  #   name: nimbus-erigon-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.nimbus-geth-1.srv.4844-devnet-6.ethpandaops.io
  #   name: nimbus-geth-1
  # - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.nimbus-besu-1.srv.4844-devnet-6.ethpandaops.io
  #   name: nimbus-besu-1

  thirdparty_endpoints: []

  config: |
    # How often to reload data from the nodes
    reload_interval = "10s"
    # If specified, a http server will serve static content here
    server_address = "0.0.0.0:{{ .Values.httpPort}}"
    # Shown in the document title, if specified
    chain_name="{{ .Values.network }}"
    # Third party providers
    infura_key          = "<INFURA_API_KEY>"
    infura_endpoint     = "https://mainnet.infura.io/v3/"
    alchemy_key         = "<ALCHEMY_API_KEY>"
    alchemy_endpoint    = "https://eth-mainnet.g.alchemy.com/v2/"
    etherscan_key       = "<ETHERSCAN_API_KEY>"
    etherscan_endpoint  = "https://api.etherscan.io/api"
    [Metrics]
    enabled = false
    endpoint = "<INFLUX_ENDPOINT>"
    username = "<INFLUX_USERNAME>"
    database  = "<INFLUX_DB_NAME>"
    password  = "<INFLUX_PASSWORD>"
    # Local or non third party connection require rpc kind
    {{- range .Values.endpoints }}
    [[clients]]
      url  = {{ .addr | quote }}
      name = {{ .name | quote }}
      kind = "rpc"
    {{- end }}
    # Third party client configuration doesn't require url
    # Kind can vary between infura, alchemy or etherscan
    # Recommended to enable rate limit for third party services
    {{- range .Values.thirdparty_endpoints }}
    [[clients]]
      name = {{ .name | quote }}
      kind = {{ .kind | quote }}
      rate_limit = {{ .rate_limit }}
    {{- end }}
