default_ethereum_client_images:
  # Consensus layer clients
  lighthouse: ethpandaops/lighthouse:realbigsean-devnetv5-48e169c
  lodestar: g11tech/lodestar@sha256:f81469af3494fd9af86e8dabfa767b6e24863c6bfb9b791afb2c78a002b499d8 # tag:blobs-2467
  nimbus: ethpandaops/nimbus:henridf-eip4844-devnet-5e6d6d6
  prysm: ethpandaops/prysm:eip4844-8efb57c
  teku: ethpandaops/teku:4844-interop-297d15c # needs update
  # Execution layer clients
  besu: robocopsgonemad/besu:4844-devnet-5-29f6e15
  geth: ethpandaops/geth:mdehoog-eip4844-a0cb931
  erigon: ethpandaops/erigon:roberto-bayardo-eip-4844-b5a7a15
  ethereumjs: ethpandaops/ethereumjs:fix-passing-versionedhashes-2f114e4
  nethermind: nethermindeth/nethermind@sha256:d3d3e2f3a853a647ebfb6332cc22126d7855df7f32422a9c50dac03596e7ef58 # tag:eip-4844-v5

default_tooling_images:
  xatu_sentry: ethpandaops/xatu:0.0.31
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:0.20.0
  tx_fuzz: ethpandaops/tx-fuzz:latest
