
goomy_rpc_urls:
  - your-execution-node:8545
goomy_private_key: ""
goomy_scenario: "combined"
goomy_extra_args: "-b 2 -t 2 --max-pending 3"


tx_fuzz_blobs_container_command:
  - blobs
  - --no-al
  - --rpc=https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.bootnode-1.srv.dencun-devnet-9.ethpandaops.io
  - --sk={{ tx_fuzz_blobs_privkey }}
  - --txcount=3

tx_fuzz_container_networks: "{{ docker_networks_shared }}"
