tx_fuzz_container_image: "{{ default_tooling_images.tx_fuzz }}"


tx_fuzz_container_command:
  - blobs
  - --no-al
  - --rpc=https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.bootnode-1.srv.dencun-devnet-9.ethpandaops.io
  - --sk={{ tx_fuzz_privkey }}
  - --txcount=3

tx_fuzz_container_networks: "{{ docker_networks_shared }}"
