name: Ansible deploy
on:
  push:
    branches:
      - skylenet/ansible-ci
    paths:
      - 'ansible/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/deploy-ansible.yaml'


jobs:
  job:
    runs-on: services-medium-cpu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Install ansible role/collection dependencies
        working-directory: ./ansible
        run: ./install_dependencies.sh
      - name: Deploy
        working-directory: ./ansible
        run: >
          ansible all -m ping
