name: Ansible lint
on:
  pull_request:
    paths:
      - 'ansible/**'
      - '.tool-versions'
  push:
    branches:
      - master
    paths:
      - 'ansible/**'
      - '.tool-versions'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Lint
        working-directory: ./ansible
        run: >
          ansible-lint playbook.yaml
          --nocolor
          --exclude vendor
          --exclude '*.sops.yaml'
          --profile production
          --skip-list 'name[play]'
          --skip-list 'meta-no-info'
          --skip-list 'yaml[line-length]'
          --skip-list 'command-instead-of-shell'
