name: Terraform lint
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.tool-versions'
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '.tool-versions'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Lint
        working-directory: ./terraform
        run: >
          terraform fmt --recursive --check --list=true --diff
