name: Helm lint
on:
  pull_request:
    paths:
      - 'kubernetes/**'
      - '.tool-versions'
  push:
    branches:
      - master
    paths:
      - 'kubernetes/**'
      - '.tool-versions'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - name: Lint
        run: >
          helm lint kubernetes/*/*
