# Ansible managed. Don't change this file manually. Template info: /roles/gen_kubernetes_config/templates/ethereum-node.yaml.j2,49f27d5 2023/07/18 13:12$

node-001:
  global:
    main:
      network: 4844-devnet-7
    checkpointSync:
      enabled: false
  nethermind:
    fullnameOverride: nethermind-lodestar-001
    enabled: true
    image:
      repository: nethermindeth/nethermind
      tag: devnet36-6c23a8
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 50Gi
    podLabels:
      network: 4844-devnet-7
      testnet: 4844-devnet-7
      ethereum_network: 4844-devnet-7
      ethereum_role: execution
      consensus_client: lodestar
      execution_client: nethermind
      ethereum_instance: nethermind-lodestar-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    extraArgs:
      - --Discovery.Bootnodes="$(tr '\n' ',' < /data/bootnodes.txt)"
      - --Init.ChainSpecPath=/data/genesis.json
      - --config=none.cfg
      - --Init.IsMining=false
      - --Pruning.Mode=None
      - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
      - --EthStats.Enabled=true
      - --EthStats.Name=k8s-nethermind-lodestar-001
      - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.ethstats_secret}>
      - --EthStats.Server=wss://ethstats.4844-devnet-7.ethpandaops.io
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          GENESIS_URI=https://config.4844-devnet-7.ethpandaops.io/el/chainspec.json;
          TRUSTED_SETUP_URI=https://config.4844-devnet-7.ethpandaops.io/trusted_setup.txt;
          BOOTNODES=https://config.4844-devnet-7.ethpandaops.io/el/bootnode.txt;
          mkdir -p /data/network-config;
          wget -O /data/network-config/bootnode.txt $BOOTNODES;
          if ! [ -f /data/network-config/genesis_init_done ];
          then
            apk update && apk add curl jq;
            wget -O /data/network-config/genesis.json $GENESIS_URI;
            wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
            cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
            touch /data/network-config/genesis_init_done;
            echo "genesis init done";
          else
            echo "genesis is already initialized";
          fi;
          echo "bootnode init done: $(cat /data/network-config/bootnode.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"

  lodestar:
    fullnameOverride: lodestar-nethermind-001
    enabled: true
    image:
      repository: g11tech/lodestar
      tag: devnet36-6c23a8
      pullPolicy: Always
    mode: "beacon"
    podLabels:
      network: 4844-devnet-7
      testnet: 4844-devnet-7
      ethereum_network: 4844-devnet-7
      ethereum_role: consensus
      consensus_client: lodestar
      execution_client: nethermind
      ethereum_instance: nethermind-lodestar-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 50Gi
    extraArgs:
      - --execution.urls=http://nethermind-lodestar-001:8551
      - --checkpointSyncUrl=https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.teku-nethermind-1.srv.4844-devnet-7.ethpandaops.io
      - --genesisStateFile=/data/testnet_spec/genesis.ssz
      - --paramsFile=/data/testnet_spec/config.yaml
      - --network.connectToDiscv5Bootnodes
      - --bootnodesFile=/data/bootnodes.txt
      - --rest.namespace='*'
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.4844-devnet-7.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.4844-devnet-7.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.4844-devnet-7.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.4844-devnet-7.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.4844-devnet-7.ethpandaops.io/cl/genesis.ssz;
          BOOTNODES=https://config.4844-devnet-7.ethpandaops.io/cl/boot_enr.yaml;
          TRUSTED_SETUP_URI=https://config.4844-devnet-7.ethpandaops.io/trusted_setup.txt;
          mkdir -p /data/network-config;
          wget -O /data/network-config/boot_enr.yaml $BOOTNODES;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          echo "bootnode init done: $(cat /data/network-config/boot_enr.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
